freeze("$(PORT_DIR)/modules")
# freeze("$(MPY_DIR)/lib/micropython-lib/micropython/drivers/bus/onewire")
# freeze("$(MPY_DIR)/lib/micropython-lib/micropython/drivers/sensor/dht")
include("$(MPY_DIR)/extmod/uasyncio/manifest.py")
include("$(MPY_DIR)/lib/micropython-lib/micropython/drivers/led/neopixel/manifest.py")
freeze("$(MPY_DIR)/lib/micropython-lib/micropython/drivers/imu/lsm6dsox")
freeze("$(MPY_LIB_DIR)/../../../../scripts/libraries/", "ble_advertising.py")
